name: Automate GKE EOL changes.

on:
  schedule:
    # Runs at midnight UTC every day
    - cron: '* * * * *'

jobs:
  build-and-merge:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Run the eol script
      run: |
        handle_diff() {
          local exit_code=$1
          if [ "$exit_code" -eq 1 ]; then
            echo "CHANGES_FOUND=1" >> $GITHUB_ENV
            return 0  # Return 0 to indicate successful completion
          fi
        }
        
        chmod +x ./gcpdiag/lint/gke/eol_parser.sh
        bash ./gcpdiag/lint/gke/eol_parser.sh > gcpdiag/lint/gke/eol.yaml
        
        # Temporarily disable exit on error
        set +e
        git diff --exit-code gcpdiag/lint/gke/eol.yaml > /dev/null
        diff_exit_code=$?
        set -e  # Re-enable exit on error
        
        # Call the handler function and pass the exit code
        handle_diff $diff_exit_code

    - name: Create Pull Request
      if: env.CHANGES_FOUND == 1
      id: create-pull-request
      uses: peter-evans/create-pull-request@v5.0.2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: gke/eol update
        title: 'gke/eol update'
        body: 'Updating gke/eol update with the new eol for GKE clusters'
        branch: 'automated-gke-eol-changes'
        delete-branch: true
        base: 'main'

    - name: Auto-merge
      if: env.CHANGES_FOUND == 1
      uses: pascalgn/automerge-action@v0.16.2
      env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
      with:
        github-token: "${{ secrets.GITHUB_TOKEN }}"
        pull-request: "${{ steps.create-pull-request.outputs.pull-request-url }}"
        merge-method: 'rebase'
        
